plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.2'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.github.davidmc24.gradle.plugin.avro' version '1.9.1'
}

group = 'ru.javaops.cloudjava'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    maven {
        url = "https://packages.confluent.io/maven/"
    }
}

ext {
    springCloudVersion ='2025.1.0'
    avroSerializerVersion='8.1.1'
    avroVersion='1.12.1'
    lokiAppenderVersion = '2.0.3'
    springRetryVersion = '2.0.12'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-aspectj'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-kafka'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation "org.springframework.retry:spring-retry:${springRetryVersion}"
    implementation "io.confluent:kafka-avro-serializer:${avroSerializerVersion}"
    implementation "org.apache.avro:avro:${avroVersion}"
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    runtimeOnly "com.github.loki4j:loki-logback-appender:${lokiAppenderVersion}"
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-aspectj-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-kafka-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.testcontainers:testcontainers-kafka'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

bootBuildImage {
    imageName = "${project.name}"
    createdDate = "now"
    environment = ["BP_JVM_VERSION": "25.*"]
    docker {
        host = "//./pipe/dockerDesktopLinuxEngine"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
